export const players = [
    {
      name: 'playerOne',
      hairColour: 'bg-black',
      shirtColour: 'bg-red-500',
      position: '2-5',
      direction: 'bottom',
      movement: 2,
      hasMoved: false,
    },
    {
      name: 'playerTwo',
      hairColour: 'bg-yellow-500',
      shirtColour: 'bg-blue-400',
      position: '4-5',
      direction: 'top',
      movement: 2,
      hasMoved: false,
    },
    {
      name: 'playerThree',
      hairColour: 'bg-red-300',
      shirtColour: 'bg-blue-400',
      position: '2-7',
      direction: 'top',
      movement: 2,
      hasMoved: false,
    },
    {
      name: 'playerFour',
      hairColour: 'bg-orange-900',
      shirtColour: 'bg-red-500',
      position: '3-6',
      direction: 'bottom',
      movement: 2,
      hasMoved: false,
    },
    {
      name: 'playerFive',
      hairColour: 'bg-yellow-900',
      shirtColour: 'bg-blue-400',
      position: '4-9',
      direction: 'bottom',
      movement: 2,
      hasMoved: false,
    },
    {
      name: 'playerSix',
      hairColour: 'bg-yellow-800',
      shirtColour: 'bg-red-500',
      position: '4-3',
      direction: 'bottom',
      movement: 2,
      hasMoved: false,
    },
  ]
